-- AlterTable
ALTER TABLE "byhour" ALTER COLUMN "windGust" DROP NOT NULL,
ALTER COLUMN "windGust" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "currenthour" ALTER COLUMN "windGust" DROP NOT NULL,
ALTER COLUMN "windGust" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "currentweather" ALTER COLUMN "windGust" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "next5days" ALTER COLUMN "windGust" DROP NOT NULL,
ALTER COLUMN "windGust" SET DATA TYPE DOUBLE PRECISION;
